<?php

$LOCAL_LANG = Array (
	'default' => Array (
		'pi_list' => 'Board, List',
		'pi_tree' => 'Board, Tree',
		'tt_board' => 'Board',
		'tt_board.subject' => 'Subject:',
		'tt_board.message' => 'Message:',
		'tt_board.parent' => 'Parent:',
		'tt_board.notify_me' => 'Notify by email:',
		'tt_board.crdate' => 'Date/Time:',
		'tt_board.cr_ip' => 'Sender IP address',
		'tt_board.reference' => 'Reference to record in another extension',
		'tt_content.pi_flexform.display_mode' => 'Display mode',
		'tt_content.pi_flexform.display_mode.1' => 'General: Help',
		'tt_content.pi_flexform.display_mode.2' => 'Category, Forum: List',
		'tt_content.pi_flexform.display_mode.3' => 'Forum: List',
		'tt_content.pi_flexform.display_mode.4' => 'Forum: Single',
		'tt_content.pi_flexform.display_mode.5' => 'Entry Form: General',
		'tt_content.pi_flexform.display_mode.6' => 'Entry Form: Reply',
		'tt_content.pi_flexform.display_mode.7' => 'Entry Form: New Thread',
		'tt_content.pi_flexform.display_mode.8' => 'Forum: Tree',
	),
	'dk' => Array (
		'tt_board' => 'Forum',
		'tt_board.subject' => 'Emne:',
		'tt_board.message' => 'Indhold:',
		'tt_board.parent' => 'Forrige:',
		'tt_board.notify_me' => 'Orientering pr. email:',
		'tt_board.crdate' => 'Dato/Tidspunkt:',
		'pi_list' => 'Forum, Liste',
		'pi_tree' => 'Forum, Træ',
	),
	'de' => Array (
		'pi_list' => 'Forum, Liste',
		'pi_tree' => 'Forum, Baum',
		'tt_board' => 'Forum',
		'tt_board.subject' => 'Titel:',
		'tt_board.message' => 'Mitteilung:',
		'tt_board.parent' => 'Vorherige:',
		'tt_board.notify_me' => 'Benachrichtigung über Email:',
		'tt_board.crdate' => 'Datum/Zeit:',
		'tt_board.cr_ip' => 'Absender IP Adresse',
		'tt_board.reference' => 'Verweis auf externen Datensatz',
		'tt_content.pi_flexform.display_mode' => 'Anzeigetyp',
		'tt_content.pi_flexform.display_mode.1' => 'Allgemein: Hilfe',
		'tt_content.pi_flexform.display_mode.2' => 'Kategorie, Forum: Liste',
		'tt_content.pi_flexform.display_mode.3' => 'Forum: Liste',
		'tt_content.pi_flexform.display_mode.4' => 'Forum: Einzel',
		'tt_content.pi_flexform.display_mode.5' => 'Eingabe Formular: Allgemein',
		'tt_content.pi_flexform.display_mode.6' => 'Eingabe Formular: Antwort',
		'tt_content.pi_flexform.display_mode.7' => 'Eingabe Formular: Neuer Eintrag',
		'tt_content.pi_flexform.display_mode.8' => 'Forum: Baum',
	),
	'no' => Array (
		'tt_board' => 'Forum',
		'tt_board.subject' => 'Emne:',
		'tt_board.message' => 'Innhold:',
		'tt_board.parent' => 'Forrige:',
		'tt_board.notify_me' => 'Orientering per Epost:',
		'tt_board.crdate' => 'Dato/tidspunkt:',
		'pi_list' => 'Forum, Liste',
		'pi_tree' => 'Forum, Tre',
	),
	'it' => Array (
		'tt_board' => 'Board',
		'tt_board.subject' => 'Soggetto:',
		'tt_board.message' => 'Messaggio:',
		'tt_board.parent' => 'Parent:',
		'tt_board.notify_me' => 'Notifica via email:',
		'tt_board.crdate' => 'Data/Ora:',
		'pi_list' => 'Forum, messaggi strutturati in una lista',
		'pi_tree' => 'Forum, messaggi strutturati ad albero',
	),
	'fr' => Array (
		'tt_board' => 'Forum',
		'tt_board.subject' => 'Sujet:',
		'tt_board.message' => 'Message:',
		'tt_board.parent' => 'Parent:',
		'tt_board.notify_me' => 'Avertir par e-mail:',
		'tt_board.crdate' => 'Date/Heure:',
		'pi_list' => 'Forum "message"',
		'pi_tree' => 'Forum "discution"',
	),
	'es' => Array (
		'tt_board' => 'Foro',
		'tt_board.subject' => 'Asunto:',
		'tt_board.message' => 'Mensaje:',
		'tt_board.parent' => 'Padre:',
		'tt_board.notify_me' => 'Notificar por email:',
		'tt_board.crdate' => 'Fecha/Hora:',
	),
	'nl' => Array (
		'tt_board' => 'Forum',
		'tt_board.subject' => 'Onderwerp:',
		'tt_board.message' => 'Bericht:',
		'tt_board.parent' => 'Bron:',
		'tt_board.notify_me' => 'Kennisgeving per email:',
		'tt_board.crdate' => 'Datum/Tijd:',
		'pi_list' => 'Forum, Lijst',
		'pi_tree' => 'Forum, Boom',
	),
	'cz' => Array (
		'tt_board' => 'Fórum',
		'tt_board.subject' => 'Pøedmìt:',
		'tt_board.message' => 'Zpráva:',
		'tt_board.parent' => 'Odvozen:',
		'tt_board.notify_me' => 'Oznámit e-mailem:',
		'tt_board.crdate' => 'Datum/Èas:',
		'pi_list' => 'Fórum, seznamové',
		'pi_tree' => 'Fórum, stromové',
	),
	'pl' => Array (
		'tt_board' => 'Forum',
		'tt_board.subject' => 'Temat:',
		'tt_board.message' => 'Wiadomo¶æ:',
		'tt_board.parent' => 'Nadrzêdny:',
		'tt_board.notify_me' => 'Powiadom emailem:',
		'tt_board.crdate' => 'Data/Czas:',
		'pi_list' => 'Forum, Lista',
		'pi_tree' => 'Forum, Drzewo',
	),
	'si' => Array (
		'tt_board' => 'Oglasna deska',
		'tt_board.subject' => 'Predmet:',
		'tt_board.message' => 'Sporoèilo:',
		'tt_board.notify_me' => 'Opozori po emailu:',
		'tt_board.crdate' => 'Datum/Ura:',
	),
	'fi' => Array (
		'tt_board' => 'Keskustelu',
		'tt_board.subject' => 'Asia:',
		'tt_board.message' => 'Viesti:',
		'tt_board.parent' => 'Edellinen:',
		'tt_board.notify_me' => 'Muistuta sähköpostitse:',
		'tt_board.crdate' => 'Päiväys/Kello',
		'pi_list' => 'Ilmoitustaulu, lista',
		'pi_tree' => 'Ilmoitustaulu, puurakenne',
	),
	'tr' => Array (
		'tt_board' => 'Ýlan tahtasý',
		'tt_board.subject' => 'Konu:',
		'tt_board.message' => 'Mesaj:',
		'tt_board.parent' => 'Eþ düzey:',
		'tt_board.notify_me' => 'E-maille haber ver:',
		'tt_board.crdate' => 'Tarih/Zaman:',
		'pi_list' => 'Ýlan tahtasi',
		'pi_tree' => 'Ýlan tahtasý, Aðaç',
	),
	'se' => Array (
	),
	'pt' => Array (
		'tt_board' => 'Quadro',
		'tt_board.subject' => 'Assunto:',
		'tt_board.message' => 'Mensagem:',
		'tt_board.parent' => 'Relativo a:',
		'tt_board.notify_me' => 'Notifique por email:',
		'tt_board.crdate' => 'Data/Hora:',
		'pi_list' => 'Quadro, Lista',
		'pi_tree' => 'Quadro, Árvore',
	),
	'ro' => Array (
	),
	'ch' => Array (
	),
	'sk' => Array (
	),
	'lt' => Array (
	),
);
?>