services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # This automatically registers all classes in the Classes folder,
  # including your UpgradeWizards via their PHP attributes.
  JambageCom\TtBoard\:
    resource: '../Classes/'
    exclude: ['../Classes/{Constants,Middleware,SessionHandler}/']

  JambageCom\TtBoard\EventListener\PageContentPreviewRenderingListener:
    tags:
      - name: event.listener
        identifier: 'ttboardCodeListener'
        event: TYPO3\CMS\Backend\View\Event\PageContentPreviewRenderingEvent
