services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  JambageCom\TtBoard\:
    resource: '../Classes/*'
    exclude: ['../Classes/{Api,Constants,Middleware}/*']

  JambageCom\TtBoard\EventListener\PageContentPreviewRenderingListener:
    tags:
      - name: event.listener
        identifier: 'ttboardCodeListener'
        event: TYPO3\CMS\Backend\View\Event\PageContentPreviewRenderingEvent
